"""Analysis modules for fantasy points calculation and recommendations."""

from .calculator import (
    BonusRole,
    PointsBreakdown,
    calculate_base_points,
    calculate_multiplier,
    calculate_player_points,
    calculate_points,
)
from .fixtures import (
    DifficultyRating,
    FixtureDifficulty,
    FixtureRecommendation,
    TeamStrength,
    calculate_fixture_difficulties,
    calculate_team_strengths,
    get_difficulty_rating,
    get_favorable_captain_picks,
    get_fixture_recommendations,
    get_team_fixture_difficulty,
)
from .form import (
    FormRecommendation,
    FormTrend,
    PlayerForm,
    calculate_form_trend,
    get_declining_players,
    get_form_recommendations,
    get_improving_players,
    get_player_form,
)
from .recommender import (
    PlayerRecommendation,
    TransferRecommendation,
    calculate_points_per_star,
    get_captain_recommendations,
    get_differential_picks,
    get_supersub_recommendations,
    get_transfer_out_candidates,
    get_transfer_suggestions,
    get_value_picks,
)
from .validator import (
    ValidationResult,
    auto_select_team,
    can_add_player,
    can_make_transfer,
    can_remove_player,
    find_affordable_transfers,
    get_available_slots_for_country,
    get_max_player_value,
    get_squad_slots_remaining,
    get_transfer_budget,
    validate_team,
)

__all__ = [
    # Calculator
    "BonusRole",
    "PointsBreakdown",
    "calculate_base_points",
    "calculate_multiplier",
    "calculate_player_points",
    "calculate_points",
    # Fixtures
    "DifficultyRating",
    "FixtureDifficulty",
    "FixtureRecommendation",
    "TeamStrength",
    "calculate_fixture_difficulties",
    "calculate_team_strengths",
    "get_difficulty_rating",
    "get_favorable_captain_picks",
    "get_fixture_recommendations",
    "get_team_fixture_difficulty",
    # Form
    "FormRecommendation",
    "FormTrend",
    "PlayerForm",
    "calculate_form_trend",
    "get_declining_players",
    "get_form_recommendations",
    "get_improving_players",
    "get_player_form",
    # Recommender
    "PlayerRecommendation",
    "TransferRecommendation",
    "calculate_points_per_star",
    "get_captain_recommendations",
    "get_differential_picks",
    "get_supersub_recommendations",
    "get_transfer_out_candidates",
    "get_transfer_suggestions",
    "get_value_picks",
    # Validator
    "ValidationResult",
    "auto_select_team",
    "can_add_player",
    "can_make_transfer",
    "can_remove_player",
    "find_affordable_transfers",
    "get_available_slots_for_country",
    "get_max_player_value",
    "get_squad_slots_remaining",
    "get_transfer_budget",
    "validate_team",
]
